services:
  nginx:
    image: nginx
    depends_on:
      - web
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./nginx/certs/nginx-selfsigned.key:/etc/ssl/certs/nginx-selfsigned.key:ro

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: web
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/public:/app/public
      - /home/dmai/projects/special-event/frontend/.next
      - /home/dmai/projects/special-event/frontend/node_modules

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
